[project]
name = "FletXr-Responsive"
version = "0.1.0"
description = "None"
readme = "README.md"
authors = [{ name = "semajbaker", email = "" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "fletxr==0.1.4.b3",
    "flet[all]==0.28.3",
    "jwt>=1.4.0",
]
